# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Llama3 8B Instruct model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Meta-Llama-3-8B-Instruct --output-dir /tmp/Meta-Llama-3-8B-Instruct --hf-token <HF_TOKEN>
#
# To launch on 4 devices, run the following command from root:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3/8B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3/8B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use 8B_full_single_device.yaml for those cases


# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /raid/lingo/models/Meta-Llama-3-8B-Instruct/original/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.arc_dataset
  source: /raid/lingo/akyurek/git/arc/data/tasks/all_in_N40_rand_transformation_black_all
  train_on_input: False
  unmask_outputs: True # we'll get loss from all outputs after the first demonstration, very hacky, tokenizer & formatting specific implementation be careful
seed: 57
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /raid/lingo/models/Meta-Llama-3-8B-Instruct
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: # recipe_state.pt
  output_dir: /raid/lingo/akyurek/git/arc/experiments/withcode_repr_v2/model_weights/
  model_type: LLAMA3
resume_from_checkpoint: False #True

# Fine-tuning arguments
batch_size: 2
epochs: 4

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  foreach: False

# lr_scheduler:
#   _component_: torchtune.modules.get_cosine_schedule_with_warmup
#   num_warmup_steps: 100

loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 4


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: /raid/lingo/akyurek/git/arc/experiments/withcode_repr_v2/logs/
log_every_n_steps: 1
log_peak_memory_stats: False
