name: integration tests

on:
  push:
    branches: [ main ]

concurrency:
  group: integration-tests-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  integration_tests:
    runs-on: 32-core-ubuntu
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: configure aws credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_torchtune_pytorch-multimodal
          aws-region: us-east-1
      - name: Download files from S3
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 14400
          command: |
            sudo swapoff -a
            sudo fallocate -l 64G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            python3 -m pip install awscli==1.32.6
            mkdir -p /tmp/test-artifacts
            aws s3 cp s3://pytorch-multimodal/llama2-7b/tokenizer.model /tmp/test-artifacts
            aws s3 cp s3://pytorch-multimodal/llama2-7b-01242024 /tmp/test-artifacts
      - name: Install dependencies
        run: |
          conda install pytorch
          python -m pip install -r requirements.txt
          python -m pip install -r dev-requirements.txt
          python -m pip install -e .
      - name: Run integration tests with coverage
        env:
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
        run: pytest integration_tests/ --cov=. --cov-report=xml --durations=5 -vv -s --llama-path /tmp/test-artifacts/llama2-7b-01242024 --tokenizer-path /tmp/test-artifacts/tokenizer.model
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
